app: link-shortener
service: link-shortener
plugins:
  - serverless-dotenv-plugin

frameworkVersion: "2"
provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

functions:
  getLink:
    handler: handler.getLink
    events:
      - http:
          path: /{link}
          method: get

  shortenLink:
    handler: handler.shortenLink
    events:
      - http:
          path: /
          method: post
    environment:
      API_TOKEN: ${env:API_TOKEN}

resources:
  Resources:
    CandidatesDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: shortname
            AttributeType: S
        KeySchema:
          - AttributeName: shortname
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: linkShortenerDB
